<a href="https://colab.research.google.com/github/ulvem/Numpy-Warm-Up-Exercises/blob/main/Numpy_Warm_Up_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

OPTIONAL TASK:
Array Creation
Warm-Up Exercises
Before you dive into the final project, we've prepared a series of basic tasks designed to serve as a warm-up, helping you to flex your NumPy muscles and get into the right mindset for the comprehensive challenge ahead.

1. Create a 3-D array with ones on the diagonal and zeros elsewhere.

2. Create an array of 3x2 numbers, filled with ones.

3. Create a matrix of shape 2x5, filled with 6s.

4. Create an array of 5, 13, 21, 29, ..., 101.

5. Create a 1-D array of 20 evenly spaced elements between 7. and 12., inclusive.

6. Create a 2-D array (4x4) whose diagonal equals [1, 2, 3, 4] and with 0's elsewhere.

7. Let x be an ndarray with the following dimensions [10, 10, 3] and let all its elements equal one. Next, reshape x so that it creates matrix (2Darray) and the size of the second dimension equals 150.

8. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

9. Let X = np.arange(1, 5).reshape((2, 2)) and calculate the determinant of X.

10. Return the sum along the diagonal of A = np.linspace(2, 16, 16).reshape(4, 4).

11. Find the inverse of np.array([[1., 2.], [3., 4.]])

12. For the following vectors,

x = np.array([4, 5, 6, 13])
y = np.array([5, 0, 6, 11])
check which elements of x are greater than those of y.

In [21]:
import numpy as np

#1 Create a 3-D array with ones on the diagonal and zeros elsewhere
array_3d = np.eye(3, 3, 3)
print("3-D array with ones on the diagonal and zeros elsewhere:\n", array_3d)


3-D array with ones on the diagonal and zeros elsewhere:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#2 Create an array of 3x2 numbers, filled with ones
array_3x2 = np.ones((3, 2))
print("Array of 3x2 numbers, filled with ones:\n", array_3x2)

Array of 3x2 numbers, filled with ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
#3 Create a matrix of shape 2x5, filled with 6s
matrix_2x5 = np.full((2, 5), 6)
print("Matrix of shape 2x5, filled with 6s:\n", matrix_2x5)

Matrix of shape 2x5, filled with 6s:
 [[6 6 6 6 6]
 [6 6 6 6 6]]


In [24]:
#4 Create an array of 5, 13, 21, 29, ..., 101
array_sequence = np.arange(5, 102, 8)
print("Array of 5, 13, 21, 29, ..., 101:\n", array_sequence)

Array of 5, 13, 21, 29, ..., 101:
 [  5  13  21  29  37  45  53  61  69  77  85  93 101]


In [25]:
#5 Create a 1-D array of 20 evenly spaced elements between 7. and 12., inclusive
array_evenly_spaced = np.linspace(7, 12, 20)
print("1-D array of 20 evenly spaced elements between 7. and 12., inclusive:\n", array_evenly_spaced)

1-D array of 20 evenly spaced elements between 7. and 12., inclusive:
 [ 7.          7.26315789  7.52631579  7.78947368  8.05263158  8.31578947
  8.57894737  8.84210526  9.10526316  9.36842105  9.63157895  9.89473684
 10.15789474 10.42105263 10.68421053 10.94736842 11.21052632 11.47368421
 11.73684211 12.        ]


In [26]:
#6 Create a 2-D array (4x4) whose diagonal equals [1, 2, 3, 4] and with 0's elsewhere
array_2d_diagonal = np.diag([1, 2, 3, 4])
print("2-D array (4x4) with diagonal [1, 2, 3, 4] and 0's elsewhere:\n", array_2d_diagonal)


2-D array (4x4) with diagonal [1, 2, 3, 4] and 0's elsewhere:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [27]:
#6 Let x be an ndarray with dimensions [10, 10, 3] and all elements equal to one
x = np.ones((10, 10, 3))
# Reshape x to a 2-D array with the second dimension equal to 150
reshaped_x = x.reshape(-1, 150)
print("Reshaped array with second dimension equal to 150:\n", reshaped_x)

Reshaped array with second dimension equal to 150:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


In [28]:
#7 Define the array
x = np.array([[1, 2, 3], [4, 5, 6]])

# Convert the array to [1 4 2 5 3 6]
converted_x = x.T.flatten()
print("Converted array:\n", converted_x)


Converted array:
 [1 4 2 5 3 6]


In [29]:
#8 Define the array
x = np.array([[1, 2, 3], [4, 5, 6]])
# Calculate the determinant of X
determinant_X = np.linalg.det(X)
print("Determinant of X:", determinant_X)

Determinant of X: -2.0000000000000004


In [30]:
#9 Define the array A
A = np.linspace(2, 16, 16).reshape(4, 4)
# Return the sum along the diagonal of A
sum_diagonal_A = np.trace(A)
print("Sum along the diagonal of A:", sum_diagonal_A)

Sum along the diagonal of A: 36.0


In [16]:
#10 Define the array
array_to_invert = np.array([[1., 2.], [3., 4.]])
# Find the inverse of the array
inverse_array = np.linalg.inv(array_to_invert)
print("Inverse of the array:\n", inverse_array)

In [31]:
#11 Define the vectors
x = np.array([4, 5, 6, 13])
y = np.array([5, 0, 6, 11])
# Check which elements of x are greater than those of y
greater_elements = x > y
print("Elements of x greater than those of y:", greater_elements)

Elements of x greater than those of y: [False  True False  True]
